name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push all images to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ sim, verilog ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: stffrdhrn/or1k-${{ matrix.repo }}-env

      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: base
          tags: or1k-base:latest

      - name: Build stripped image
        uses: docker/build-push-action@v4
        with:
          context: stripped
          tags: or1k-base-stripped:latest

      - name: Build environment image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.repo }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
